### ISSUE TITLE
triage & maintainers need permissions to transfer issues across repos

### ISSUE THREAD

**Issue by handrews** [OAI/community#13]
@webron I'm guessing we need your admin powers on this as well as I'm not sure anyone else has access to all the repos needed.

In today's call we agreed to remove some issue labels from the spec repo, but this requires @OAI/triage and @OAI/openapi-maintainers being able to transfer some of the labeled issues to other repos, specifically:

* community (this repo)
* learn.openapis.org
* Outreach
* Tooling
* oascomply
* Overlay-Specification
* sig-*

Could this ability be added for both of those groups (at the moment, I don't think adding to triage automatically empowers maintainers).

**Comment by webron** [comment]
@handrews any concerns with limiting this to @OAI/openapi-maintainers only for now? The @OAI/triage team is set with github's triage permissions that do not allow manipulating labels or transferring issues, but also don't allow merging/modifying PRs. Feels like elevating the team's permissions would go against what triage means by Github's standards.

I believe the active members of the triage team are part of the maintainers team so it shouldn't hinder anyone's work. We can always look into adding more people to the maintainers team.

**Comment by handrews** [comment]
@webron maintainers only for now would be great and would unblock things - thanks for the quick reply!

I'm pretty vague on how they're configured and did not intend to propose adding new privileges.  We do plan to revisit the roles once the new TSC is in place:

* https://github.com/OAI/OpenAPI-Specification/issues/3523
* https://github.com/OAI/OpenAPI-Specification/issues/3524

**Comment by webron** [comment]
@handrews ok, I've added @OAI/openapi-maintainers to all the requested repos, with the `Write` permission, and not the `Maintain` permission, since that's how it was set for the OAS repo. Once we define the roles better, we can make the decision of changing the permissions set, it's easy enough to do.

We should also have a task to clean out some of the users/permissions that we currently have. I've noticed some inactive users with access, and we should probably remove those to not have any potential destructive actions (intentional or not).

Since you're a member of @OAI/openapi-maintainers, please run a test to see if you can access what's needed. Happy to look into any issues.

**Comment by handrews** [comment]
Thanks, @webron - the only one I don't see is Outreach.  If you left that one off intentionally, there are [a few issues](https://github.com/OAI/OpenAPI-Specification/labels/Outreach) that need moving, and @swaldron58 says [he doesn't have permissions either](https://github.com/OAI/Outreach/issues/35).  As long as _someone_ can move them it will be fine with me.

But I can see the other repos as transfer options here, and this repo as a transfer option elsewhere. 🎉

**Comment by webron** [comment]
No, I see maintainers in the Outreach repo, so it should be fine. Regardless, I'll transfer those issues quickly now, no problem. Please let me know if you run into any more issues.

**Comment by handrews** [comment]
Thanks again, Ron!  I do seem to have maintainer privileges in the Outreach repo, but it's not showing up as a possible transfer destination from other repos.  I seem to recall @earth2marsh and I had this problem with the sig-moonwalk repo at first?  There might be some other setting that's also involved.

Anyway, I doubt we'll get many Outreach issues in the spec repo, so this is close enough to done for me :-)
