### ISSUE TITLE
[Request to Create SIG]: 

### ISSUE THREAD

**Issue by namdeirf** [OAI/community#3]
### Contact Details

@namdeirf

### Give your SIG a unique name, a one or two word descriptor.

This is a test of the SIG creation process, this is only a test

### Give an overview of your SIG.

We want to test the 'if you build it, they will come' mindset.

### Statement of Work

The goal is to build a baseball field in Iowa.

### SIG Class

Industry SIG

### History

A new group

### How often do you intend to need to meet

Every other week

### Teleconference link

No

### Slack

No

### discord

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lornajane** [comment]
Closing the test issue :)
